---
# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: appcenter-review-parse
description: Parses information for the appcenter-review repository
author: elementary

branding:
  icon: crosshair
  color: green

runs:
  using: node20
  main: dist/index.js

inputs:
  token:
    description: A GitHub API token
    required: false
    default: ${{ github.token }}

  workspace:
    description: The git repository to parse for files
    required: false
    default: ${{ github.workspace }}

  regex:
    description: JS Regex to parse the file path into usable data
    required: false
    default: |
      applications\/(?<rdnn>[a-zA-Z0-9\.]+)\/(?<version>.*)\.json

outputs:
  rdnn:
    description: RDNN of the application we are reviewing
  version:
    description: Semver version of the application we are reviewing
  source:
    description: The source code url for the code we are reviewing
  commit:
    description: The commit ref of the source code we are reviewing
  end-of-life:
    description: Mark build as end-of-life
  end-of-life-rebase:
    description: "Mark new refs as end-of-life. This one takes an ID that supersedes the current one. By the user's request, the application data may be preserved for the new application. Note, this is actually a prefix match, so if you say org.the.app=org.new.app, then something like org.the.app.Locale will be rebased to org.new.app.Locale."
